sensors:
  - default_sensor
default_sensor:
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: ""
  image_topic: /camera/depth/color/points
  max_update_rate: 5.0
  near_clipping_plane_distance: 0.0
  padding_offset: 0.0
  padding_scale: 0.0
  queue_size: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  shadow_threshold: 0.0
